language: cpp

compiler:
  - gcc

sudo: required
dist: xenial

install:
  - sudo apt-get install -qq qt5-default qt5-qmake cmake

script:
  - qmake src/QMaterialIcons.pro
  - make
  - cmake .
  - make

notifications:
  email: false
